# Generated by Django 5.1 on 2025-10-18 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.PositiveIntegerField(verbose_name='SMTP Port')),
                ('smtp_username', models.CharField(max_length=255, verbose_name='SMTP Username')),
                ('smtp_password', models.CharField(max_length=255, verbose_name='SMTP Password')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Email người gửi')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Sử dụng TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Sử dụng SSL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('last_test_success', models.BooleanField(blank=True, null=True, verbose_name='Test cuối thành công')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày test cuối')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_configs', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_email_configs', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Cấu hình Email',
                'verbose_name_plural': 'Cấu hình Email',
                'ordering': ['-updated_at'],
            },
        ),
    ]
