# Generated by Django 5.1 on 2025-10-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_auto_20251018_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='auth_method',
            field=models.CharField(choices=[('none', 'Không cần xác thực'), ('normal', 'Username và Password')], default='normal', max_length=10, verbose_name='SMTP Outgoing Authentication'),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='smtp_conn_timeout',
            field=models.PositiveIntegerField(default=60000, verbose_name='SMTP - Communication Timeout'),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='smtp_timeout',
            field=models.PositiveIntegerField(default=60000, verbose_name='SMTP - Timeout'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SMTP Password'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SMTP Username'),
        ),
    ]
