# Generated by Django 5.1 on 2025-10-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_emailconfiguration_auth_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã định danh duy nhất cho mẫu email, ví dụ: request_created', max_length=50, unique=True, verbose_name='Mã mẫu')),
                ('type', models.CharField(choices=[('request_created', 'Yêu cầu cấp phát mới'), ('pending_approval', 'Yêu cầu chờ phê duyệt'), ('request_approved', 'Yêu cầu đã được phê duyệt'), ('request_rejected', 'Yêu cầu bị từ chối'), ('warehouse_scheduled', 'Kho đã hẹn lịch cấp phát'), ('request_completed', 'Yêu cầu đã hoàn thành'), ('other', 'Mẫu khác')], default='other', max_length=30, verbose_name='Loại mẫu')),
                ('name', models.CharField(help_text='Tên hiển thị của mẫu email', max_length=100, verbose_name='Tên mẫu')),
                ('subject', models.CharField(help_text='Tiêu đề của email sẽ được gửi', max_length=255, verbose_name='Tiêu đề email')),
                ('content', models.TextField(help_text='Nội dung của email. Có thể sử dụng các biến với cú pháp {{variable_name}}', verbose_name='Nội dung email')),
                ('description', models.TextField(blank=True, help_text='Mô tả về mẫu email và trường hợp sử dụng', null=True, verbose_name='Mô tả')),
                ('is_html', models.BooleanField(default=True, help_text='Email được gửi ở định dạng HTML thay vì text thuần túy', verbose_name='Định dạng HTML')),
                ('is_active', models.BooleanField(default=True, help_text='Mẫu email này có đang được sử dụng hay không', verbose_name='Kích hoạt')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Danh sách các biến có thể sử dụng trong mẫu này ở định dạng JSON', verbose_name='Danh sách biến')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mẫu email',
                'verbose_name_plural': 'Mẫu email',
                'ordering': ['type', 'name'],
            },
        ),
    ]
