# Generated by Django 5.2.7 on 2025-10-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='from_name',
            field=models.CharField(default='Hệ thống quản lý kho', max_length=255, verbose_name='Tên người gửi'),
        ),
    ]
