# Generated by Django 5.2.7 on 2025-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0005_emailconfiguration_from_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='default_cc',
            field=models.TextField(blank=True, help_text='Danh sách địa chỉ email CC, phân tách bằng dấu phẩy', null=True, verbose_name='CC mặc định'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='default_recipients',
            field=models.TextField(blank=True, help_text='Danh sách địa chỉ email, phân tách bằng dấu phẩy. Ví dụ: a@x.com,b@y.com', null=True, verbose_name='Người nhận mặc định'),
        ),
    ]
