# Generated by Django 5.2.7 on 2025-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0006_emailtemplate_default_cc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('request_created', 'Yêu cầu cấp phát mới'), ('pending_approval', 'Yêu cầu chờ phê duyệt'), ('request_approved', 'Yêu cầu đã được phê duyệt'), ('request_rejected', 'Yêu cầu bị từ chối'), ('warehouse_scheduled', 'Kho đã hẹn lịch cấp phát'), ('request_completed', 'Yêu cầu đã hoàn thành'), ('low_stock_alert', 'Cảnh báo tồn kho thấp'), ('other', 'Mẫu khác')], default='other', max_length=30, verbose_name='Loại mẫu'),
        ),
    ]
