# Generated by Django 5.2.7 on 2025-10-22 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0007_alter_emailtemplate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_frequency', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng'), ('manual', 'Thủ công')], default='manual', max_length=20, verbose_name='Tần suất backup')),
                ('backup_time', models.TimeField(blank=True, null=True, verbose_name='Thời gian backup (cho tự động)')),
                ('include_database', models.BooleanField(default=True, verbose_name='Backup database')),
                ('include_media', models.BooleanField(default=True, verbose_name='Backup media files')),
                ('max_backups_keep', models.IntegerField(default=10, help_text='Số lượng backup tối đa được lưu trữ', verbose_name='Số lượng backup giữ lại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt backup tự động')),
                ('last_backup_date', models.DateTimeField(blank=True, null=True, verbose_name='Lần backup cuối')),
                ('last_backup_success', models.BooleanField(blank=True, null=True, verbose_name='Backup cuối thành công')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_configs_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_configs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Cấu hình Backup',
                'verbose_name_plural': 'Cấu hình Backup',
                'db_table': 'backup_configuration',
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Toàn bộ'), ('database', 'Database only'), ('media', 'Media only')], default='full', max_length=20, verbose_name='Loại backup')),
                ('backup_name', models.CharField(max_length=255, verbose_name='Tên file backup')),
                ('backup_file', models.FileField(blank=True, null=True, upload_to='backups/', verbose_name='File backup')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Kích thước (bytes)')),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Thông báo lỗi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Backup tự động')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày restore')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_restored', to=settings.AUTH_USER_MODEL, verbose_name='Người restore')),
            ],
            options={
                'verbose_name': 'Lịch sử Backup',
                'verbose_name_plural': 'Lịch sử Backup',
                'db_table': 'backup_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
