# Generated by Django 5.1 on 2025-10-17 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sm', 'admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email người quản lý'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Họ tên người quản lý'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bộ phận'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sm', 'SM (Senior Manager)'), ('admin', 'Quản trị viên'), ('manager', 'Quản lý'), ('staff', 'Nhân viên'), ('viewer', 'Chỉ xem')], default='staff', max_length=10, verbose_name='Vai trò'),
        ),
    ]
