# Generated by Django 5.2.7 on 2025-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_approve',
            field=models.BooleanField(default=False, help_text='Yêu cầu của user này sẽ tự động được phê duyệt và chuyển thẳng đến kho xử lý', verbose_name='Tự động phê duyệt'),
        ),
    ]
