# Generated by Django 5.1 on 2025-10-16 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã bộ phận')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bộ phận')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bộ phận',
                'verbose_name_plural': 'Bộ phận',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('first_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], default='M', max_length=1, verbose_name='Giới tính')),
                ('id_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CMND/CCCD')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày vào làm')),
                ('status', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='Bộ phận')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['employee_id', 'last_name', 'first_name'],
            },
        ),
    ]
