# Generated by Django 5.1 on 2025-10-16 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên đơn vị')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Viết tắt')),
            ],
            options={
                'verbose_name': 'Đơn vị tính',
                'verbose_name_plural': 'Đơn vị tính',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kho')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('active', models.BooleanField(default=True, verbose_name='Còn hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Kho',
                'verbose_name_plural': 'Kho',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_code', models.CharField(max_length=50, verbose_name='Mã cột')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Cột kho',
                'verbose_name_plural': 'Cột kho',
                'ordering': ['column_code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng hiện tại')),
                ('minimum_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tối thiểu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='Danh mục')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.purchaseorder', verbose_name='Đơn đặt hàng')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.unit', verbose_name='Đơn vị tính')),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.warehousecolumn', verbose_name='Vị trí trong kho')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['product_code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_code', models.CharField(max_length=50, verbose_name='Mã dãy')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='inventory.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Dãy kho',
                'verbose_name_plural': 'Dãy kho',
                'ordering': ['row_code'],
                'unique_together': {('warehouse', 'row_code')},
            },
        ),
        migrations.AddField(
            model_name='warehousecolumn',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='inventory.warehouserow', verbose_name='Dãy kho'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousecolumn',
            unique_together={('row', 'column_code')},
        ),
    ]
