# Generated by Django 5.1 on 2025-10-17 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_purchase_order_stockreceipt_and_more'),
        ('suppliers', '0002_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceiptitem',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='suppliers.purchaseorderitem', verbose_name='Chi tiết đơn hàng'),
        ),
        migrations.AddField(
            model_name='stockreceiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockreceipt', verbose_name='Phiếu nhập kho'),
        ),
    ]
