# Generated by Django 5.2.7 on 2025-10-21 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockreceiptitem_purchase_order_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=50, unique=True, verbose_name='Mã giao dịch')),
                ('transaction_type', models.CharField(choices=[('IN', 'Nhập kho'), ('OUT', 'Xuất kho'), ('ADJUST', 'Điều chỉnh')], max_length=10, verbose_name='Loại giao dịch')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giao dịch')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('reference_code', models.CharField(blank=True, help_text='Mã PO hoặc mã xuất kho', max_length=100, null=True, verbose_name='Mã tham chiếu')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Giao dịch kho',
                'verbose_name_plural': 'Giao dịch kho',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
