# Generated by Django 5.2.7 on 2025-10-20 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_stockreceiptitem_purchase_order_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_code', models.CharField(max_length=50, unique=True, verbose_name='Mã kiểm kê')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('audit_date', models.DateField(verbose_name='Ngày kiểm kê')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('in_progress', 'Đang kiểm kê'), ('completed', 'Hoàn thành')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiếu kiểm kê',
                'verbose_name_plural': 'Phiếu kiểm kê',
                'db_table': 'reports_inventory_audit',
                'ordering': ['-audit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField(verbose_name='Số lượng hệ thống')),
                ('actual_quantity', models.IntegerField(blank=True, null=True, verbose_name='Số lượng thực tế')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.inventoryaudit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Chi tiết kiểm kê',
                'verbose_name_plural': 'Chi tiết kiểm kê',
                'db_table': 'reports_inventory_audit_item',
                'unique_together': {('audit', 'product')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('opening_stock', models.IntegerField(default=0, verbose_name='Tồn đầu tháng')),
                ('closing_stock', models.IntegerField(default=0, verbose_name='Tồn cuối tháng')),
                ('total_received', models.IntegerField(default=0, verbose_name='Tổng nhập')),
                ('total_issued', models.IntegerField(default=0, verbose_name='Tổng xuất')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Đã chốt')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày chốt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Snapshot tồn kho tháng',
                'verbose_name_plural': 'Snapshot tồn kho tháng',
                'db_table': 'reports_monthly_inventory_snapshot',
                'ordering': ['-year', '-month', 'product__name'],
                'indexes': [models.Index(fields=['year', 'month'], name='reports_mon_year_9e975c_idx'), models.Index(fields=['product', 'year', 'month'], name='reports_mon_product_6c9459_idx')],
                'unique_together': {('product', 'year', 'month')},
            },
        ),
    ]
