# Generated by Django 5.1 on 2025-10-16 05:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã nhà cung cấp')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Tên người liên hệ')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='Mã PO')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đặt hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('completed', 'Hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('po_image', models.ImageField(blank=True, null=True, upload_to='purchase_orders/', verbose_name='Hình ảnh PO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='suppliers.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Đơn đặt hàng',
                'verbose_name_plural': 'Đơn đặt hàng',
                'ordering': ['-order_date', 'po_number'],
            },
        ),
    ]
