# Generated by Django 5.1 on 2025-10-18 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', 'custom_migration'),
        ('inventory', '0003_stockreceiptitem_purchase_order_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=20, unique=True, verbose_name='Mã yêu cầu')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề yêu cầu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('pending', 'Chờ phê duyệt'), ('approved', 'Đã phê duyệt'), ('rejected', 'Bị từ chối'), ('scheduled', 'Đã lên lịch'), ('completed', 'Đã hoàn thành'), ('canceled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Ngày mong muốn nhận')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến cấp phát')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('approval_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú phê duyệt')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Lý do từ chối')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo yêu cầu')),
                ('warehouse_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_managed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý kho phụ trách')),
            ],
            options={
                'verbose_name': 'Yêu cầu cấp phát',
                'verbose_name_plural': 'Yêu cầu cấp phát',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to='employees.employee', verbose_name='Nhân viên')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_employees', to='inventory_requests.inventoryrequest', verbose_name='Yêu cầu')),
            ],
            options={
                'verbose_name': 'Nhân viên cần cấp phát',
                'verbose_name_plural': 'Nhân viên cần cấp phát',
                'unique_together': {('request', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField(verbose_name='Số lượng yêu cầu')),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng phê duyệt')),
                ('issued_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng đã cấp phát')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='inventory.product', verbose_name='Sản phẩm')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_requests.inventoryrequest', verbose_name='Yêu cầu')),
            ],
            options={
                'verbose_name': 'Sản phẩm yêu cầu',
                'verbose_name_plural': 'Sản phẩm yêu cầu',
                'unique_together': {('request', 'product')},
            },
        ),
    ]
