# Generated by Django 5.1 on 2025-10-18 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', 'custom_migration'),
        ('inventory', '0003_stockreceiptitem_purchase_order_item_and_more'),
        ('inventory_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng yêu cầu')),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng phê duyệt')),
                ('issued_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng đã cấp phát')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='employees.employee', verbose_name='Nhân viên')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests', to='inventory.product', verbose_name='Sản phẩm')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_products', to='inventory_requests.inventoryrequest', verbose_name='Yêu cầu')),
            ],
            options={
                'verbose_name': 'Phân bổ sản phẩm cho nhân viên',
                'verbose_name_plural': 'Phân bổ sản phẩm cho nhân viên',
                'unique_together': {('request', 'employee', 'product')},
            },
        ),
    ]
