# Generated by Django 5.1 on 2025-10-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0002_employeeproductrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrequest',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giờ dự kiến cấp phát'),
        ),
    ]
