# Generated by Django 5.1 on 2025-10-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0003_alter_inventoryrequest_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm lên lịch'),
        ),
    ]
