# Generated by Django 5.1 on 2025-10-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0004_inventoryrequest_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='schedule_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú lên lịch'),
        ),
    ]
